const $=(s)=>document.querySelector(s);
let speed=0;
function accelerate(){speed=Math.min(30,speed+Math.floor(Math.random()*6)+2);const n=$("#speed"),bar=$(".speedfill");if(n)n.textContent=speed;if(bar)bar.style.width=(speed/30*100)+"%";const msg=$("#speedMsg");if(msg)msg.textContent=speed<10?"Calentando... 🚶":speed<20?"Ya vamos rápido... 😳":speed<28?"¡Hay que correr para seguirle el paso! 😂":"Velocidad desbloqueada: imposible alcanzarla ✨"}
const fruitMessages={"🍓":"Una elección bastante dulce. ✨","🍊":"Naranja: energía para seguir el día. 🍊","🍉":"Sandía: oficialmente modo verano activado.","🍌":"Banana: combustible para la aventura. ⚡","🍎":"Una clásica nunca falla. 🍎","🍍":"Piña: personalidad tropical desbloqueada. 🌴"};
function fruitPick(f){const o=$("#fruitOutput");if(o)o.textContent=fruitMessages[f]||"Buena elección. ✨"}function randomFruit(){const keys=Object.keys(fruitMessages),f=keys[Math.floor(Math.random()*keys.length)];fruitPick(f)}
const rapLines=[["Pucca va caminando","con estilo improvisando","dice que hoy va a rapear","y nos toca escuchar <3"],["Una fruta por aquí","una rima por allá","si la métrica se escapa","igual se vuelve a intentar 🎤"],["Con música y buena vibra","la tarde puede mejorar","si la rima sale chistosa","¡eso también es improvisar!"],["Arte, baile y canción","todo puede combinar","y si aparece un beat","hay que dejarlo sonar 🎧"]];
function newRap(){const r=rapLines[Math.floor(Math.random()*rapLines.length)],o=$("#rapOutput");if(o)o.innerHTML=r.join("<br>")}
const trivia=[{q:"¿Qué objeto está muy ligado al ambiente de Soy Luna?",a:["Patines","Guitarra eléctrica","Tabla de surf","Cámara"],c:0},{q:"¿Qué actividad es central en muchas escenas de la serie?",a:["Patinaje","Boxeo","Natación","Escalada"],c:0},{q:"¿Qué elemento encaja con una tarde musical de Soy Luna?",a:["Canciones y patines","Cocina y ajedrez","Robótica","Astronomía"],c:0}];
let ti=0;function renderTrivia(){const q=$("#question"),opts=$("#options");if(!q||!opts)return;q.textContent=trivia[ti].q;opts.innerHTML="";trivia[ti].a.forEach((x,i)=>{const b=document.createElement("button");b.textContent=x;b.onclick=()=>answerTrivia(i);opts.appendChild(b)})}
function answerTrivia(i){const result=$("#triviaResult");if(i===trivia[ti].c)result.textContent="¡Correcto! 🌙✨";else result.textContent="Casi... pero todavía queda otra oportunidad. 💫";setTimeout(()=>{ti=(ti+1)%trivia.length;renderTrivia()},900)}
document.addEventListener("DOMContentLoaded",renderTrivia);